---
- name: Configure IPv6 Preference
  import_playbook: ../configure_ipv6.yml

- name: Install and configure OpenLDAP
  hosts: ldap_server
  tasks:
    - import_role:
        name: confluent.test.ldap

- name: Deploy Static KRaft Cluster
  import_playbook: confluent.platform.all
  vars:
    kraft_dynamic_quorum_enabled: false
