---
- name: Extract ClusterId from meta.properties on KRaft Controller
  slurp:
    src: "{{ kafka_controller_final_properties['log.dirs'] }}/meta.properties"
  delegate_to: "{{ groups.kafka_controller[0] }}"
  register: uuid_broker

- name: Get existing master key from override.conf
  include_role:
    name: common
    tasks_from: get_masterkey.yml
  vars:
    systemd_override_path: "{{ kafka_broker.systemd_override }}"
  when: kafka_broker_secrets_protection_enabled|bool
  tags:
    - get_existing_masterkey_from_override_conf

- name: Format Storage Directory
  command: "{{ binary_base_path }}/bin/kafka-storage format -t={{ clusterid }} -c {{ kafka_broker.config_file }} --ignore-formatted"
  environment: "{{ {'CONFLUENT_SECURITY_MASTER_KEY': existing_masterkey} if kafka_broker_secrets_protection_enabled|bool and existing_masterkey | default('') != '' else {} }}"
  register: format_meta
  changed_when: format_meta.rc == 0
  no_log: "{{mask_secrets|bool}}"
  vars:
    clusterid: "{{ (uuid_broker['content'] | b64decode).partition('cluster.id=')[2].partition('\n')[0] }}"
