FROM {{ item.image }}

RUN yum -y install java-1.8.0-openjdk

RUN echo $'[Confluent.dist]\n\
name=Confluent repository (dist)\n\
baseurl=https://packages.confluent.io/rpm/5.3/7\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.3/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl=https://packages.confluent.io/rpm/5.3\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.3/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common-5.3.0-1 \
      confluent-rebalancer-5.3.0-1 \
      confluent-rest-utils-5.3.0-1 \
      confluent-metadata-service-5.3.0-1  \
      confluent-kafka-2.12-5.3.0-1 \
      confluent-kafka-connect-elasticsearch-5.3.0-1 \
      confluent-kafka-connect-jdbc-5.3.0-1 \
      confluent-kafka-connect-jms-5.3.0-1 \
      confluent-kafka-connect-replicator-5.3.0-1 \
      confluent-kafka-connect-s3-5.3.0-1 \
      confluent-kafka-connect-storage-common-5.3.0-1 \
      confluent-kafka-rest-5.3.0-1 \
      confluent-ksql-5.3.0-1 \
      confluent-schema-registry-5.3.0-1 \
      confluent-security-5.3.0-1 \
      confluent-control-center-fe-5.3.0-1 \
      confluent-control-center-5.3.0-1 \
      confluent-schema-registry-5.3.0-1
