---
- name: Verify - kafka_connect1 is not scaled yet
  hosts: kafka-connect1
  gather_facts: false
  tasks:
    - name: Get connectors details
      uri:
        url: "https://kafka-connect1:8083/connectors?expand=status"
        status_code: 200
        validate_certs: false
        client_cert: /var/ssl/private/kafka_connect.crt
        client_key: /var/ssl/private/kafka_connect.key
      register: connect_cluster_response
    - set_fact:
        hosts_connect4: '{{ connect_cluster_response.json["sample-connector-ssl"].status.tasks | map(attribute="worker_id") | map("regex_search",".*connect4.*") | select("string") | list  }}'
    - name: Assert that there are no hosts with connect4 name in workers list
      assert:
        that: "hosts_connect4 | length == 0"
        fail_msg: "There should not be connect4 in ssl cluster yet"

- name: Verify - control_center_next_gen before scale-up
  hosts: control_center_next_gen
  gather_facts: false
  tasks:
    - name: Check line connect cluster1 should not have additional nodes yet
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.connect.connect-cluster1.cluster
        expected_value: http://kafka-connect2:8083

    - name: Check line connect cluster named ssl should not have connect4 setup yet
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.connect.connect-ssl.cluster
        expected_value: https://kafka-connect1:8083

- name: Add new connect Node into in-memory inventory to scale-up
  hosts: all
  gather_facts: false
  tasks:
    - name: Add new Connect Node kafka-connect4 to ssl cluster
      add_host:
        hostname: kafka-connect4
        groups:
          - kafka_connect
          - ssl

- name: Converge
  import_playbook: confluent.platform.all
