FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs python3 --releasever 9 --setopt install_weak_deps=false --nodocs -y && \
    dnf --installroot /mnt/rootfs clean all && \
    rpm --root /mnt/rootfs -e --nodeps setup

FROM {{ item.image }}
COPY --from=ubi-micro-build /mnt/rootfs /
LABEL maintainer="CP Ansible"
ENV container docker


VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd"]