FROM {{ item.image }}
LABEL maintainer="CP Ansible"
ENV container docker
ENV DEBIAN_FRONTEND=noninteractive

# Install systemd and basic requirements for Ansible
RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      systemd \
      systemd-sysv \
      python3 \
      python3-pip \
      python3-apt \
      sudo \
      wget \
      curl \
      gnupg \
      apt-transport-https \
      ca-certificates \
      software-properties-common \
      rsync \
      openssl \
      unzip \
      procps \
      iproute2 \
      openjdk-17-jdk

# Clean up systemd
RUN rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

