FROM {{ item.image }}

RUN echo 'deb [check-valid-until=no] http://archive.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list

RUN sed -i s/ftp.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i s/security.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i '/stretch-updates/d' /etc/apt/sources.list
RUN sed -i s/ftp.debian.org/archive.debian.org/g /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-11-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl \
      git \
      libssl-dev \
      zlib1g-dev \
      libbz2-dev \
      libreadline-dev \
      libsqlite3-dev \
      libffi-dev \
      libncurses5-dev \
      liblzma-dev \
      libgdbm-dev \
      libnss3-dev \
      libdb-dev

# Hack to fix cacerts on debian hosts, preventing confluenthub installs from working
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts && \
    /var/lib/dpkg/info/ca-certificates-java.postinst configure

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN wget -qO - {{ CLIENT_REPO_URL }}/clients/deb/archive.key | sudo apt-key add - && \
    add-apt-repository "deb {{ CLIENT_REPO_URL }}/clients/deb/ stretch stable main" && \
    apt-get update

RUN wget -qO - {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }}/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }} stable main" && \
    apt-get update

RUN curl https://pyenv.run | bash

# Set up pyenv environment variables
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# Install Python 3.6 using pyenv
RUN pyenv install 3.6.15 && \
    pyenv global 3.6.15 && \
    ln -sf /root/.pyenv/versions/3.6.15/bin/python3.6 /usr/bin/python3

RUN rm /usr/bin/lsb_release

# Ensure pip is installed and linked to the default Python interpreter
RUN apt-get install --no-install-recommends --yes python-pip && \
    ln -sf /usr/bin/pip /usr/bin/pip2 && \
    ln -sf /usr/bin/python /usr/bin/python2

RUN apt-get install --yes \
     confluent-common \
     confluent-hub-client \
     confluent-rebalancer \
     confluent-rest-utils \
     confluent-metadata-service \
     confluent-server \
     confluent-kafka-connect-replicator \
     confluent-kafka-rest \
     confluent-ksqldb \
     confluent-schema-registry \
     confluent-security \
     confluent-control-center-fe \
     confluent-control-center \
     confluent-schema-registry-plugins
