FROM {{ item.image }}

RUN echo 'deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      openjdk-11-jdk \

RUN mkdir -p /etc/ssl/certs/java/cacerts
# Hack to fix cacerts on debian hosts, preventing confluenthub installs from working
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts && \
    /var/lib/dpkg/info/ca-certificates-java.postinst configure