FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y wget gnupg vim jq curl && \
    apt-get install -y dirmngr

{% set ARCHITECTURE_SHORTHAND = lookup('env', 'ARCHITECTURE_SHORTHAND') | default ('x64', true) %}

RUN curl -sL "https://api.adoptium.net/v3/binary/latest/25/ga/linux/{{ ARCHITECTURE_SHORTHAND }}/jdk/hotspot/normal/eclipse?project=jdk" -o /tmp/jdk25.tar.gz && \
    tar xzf /tmp/jdk25.tar.gz -C /opt/ && \
    mv /opt/jdk-25* /opt/jdk25 && \
    ln -s /opt/jdk25/bin/java /usr/bin/java && \
    rm -f /tmp/jdk25.tar.gz
