FROM {{ item.image }}

# replace mirror.centos.org with vault.centos.org as centos7 is eol and this url does not work now.
RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
RUN yum update -y

RUN yum -y install java-11-openjdk \
      rsync \
      openssl
