FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl

{% set PACKAGE_VER = lookup('env', 'VERSION') | default('7.0.1', true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('http://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz {{ COMMON_REPO_URL }}/archive/{{ REPO_VER }}/confluent-{{ PACKAGE_VER }}.tar.gz && \
    tar xzf /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz
