FROM {{ item.image }}

RUN echo 'deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-11-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

RUN wget -qO - https://packages.confluent.io/clients/deb/archive.key | sudo apt-key add - && \
    add-apt-repository "deb https://packages.confluent.io/clients/deb/ stretch stable main" && \
    apt-get update

RUN wget -qO - https://packages.confluent.io/deb/6.2/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.2 stable main" && \
    apt-get update

RUN apt-get install --yes \
     confluent-common \
     confluent-hub-client \
     confluent-rebalancer \
     confluent-rest-utils \
     confluent-metadata-service \
     confluent-server \
     confluent-kafka-connect-replicator \
     confluent-kafka-rest \
     confluent-ksqldb \
     confluent-schema-registry \
     confluent-security \
     confluent-control-center-fe \
     confluent-control-center \
     confluent-schema-registry
