FROM {{ item.image }}

# Add the OpenJDK repository to remove flakiness
RUN add-apt-repository -y "ppa:openjdk-r/ppa" && \
    apt-get update

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-11-jdk wget gnupg && \
    apt-get install -y dirmngr
