FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-11-jdk wget gnupg

RUN wget -qO - https://packages.confluent.io/clients/deb/archive.key | sudo apt-key add - && \
    add-apt-repository "deb https://packages.confluent.io/clients/deb/ stretch main" && \
    apt-get update

RUN wget -qO - https://packages.confluent.io/deb/7.0/archive.key | sudo apt-key add - && \
   add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/7.0 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry
