FROM {{ item.image }}


RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      procps \
      software-properties-common \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl \
      sudo \
      wget \
      tar \
      systemd systemd-sysv dbus \
      vim \
      jq

{% set ARCHITECTURE_SHORTHAND = lookup('env', 'ARCHITECTURE_SHORTHAND') | default ('x64', true) %}

RUN wget https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-{{ ARCHITECTURE_SHORTHAND }}_bin.tar.gz && \
    tar xvf openjdk-21.0.2_linux-{{ ARCHITECTURE_SHORTHAND }}_bin.tar.gz && \
    sudo mv jdk-21*/ /opt/jdk21 && \
    ln -s /opt/jdk21/bin/java /usr/bin/java && \
    rm -rf openjdk-21.0.2_linux-{{ ARCHITECTURE_SHORTHAND }}_bin.tar.gz

# Create a systemd service for running in the container
RUN mkdir -p /etc/systemd/system/docker.service.d && \
    echo -e "[Service]\nExecStart=\nExecStart=/lib/systemd/systemd" > /etc/systemd/system/docker.service.d/override.conf

# Set the default command to start systemd
CMD ["/lib/systemd/systemd"]

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN wget -qO - {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }}/archive.key | sudo apt-key add - && \
    add-apt-repository "deb {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }} stable main" && \
    apt-get update