FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y software-properties-common && \
    apt-get install -y openjdk-17-jdk wget gnupg && \
    apt-get install -y dirmngr
