FROM {{ item.image }}

# CentOS 7 is EOL: mirrorlist.centos.org is decommissioned (DNS gone) and
# mirror.centos.org is retired. Disable the dead mirrorlists and point every
# repo at the frozen vault.centos.org tree over HTTPS -- plain http now
# 301-redirects to https and CentOS 7's old curl then gets a 403 from CloudFront.
# vault/EPEL are also flaky (intermittent CDN 403s / empty replies); since every
# OS package is baked into this image below, mark these repos skip_if_unavailable
# so a metadata refresh miss at converge time can't abort the run.
RUN sed -i \
      -e 's|^mirrorlist=|#mirrorlist=|g' \
      -e 's|^#\s*baseurl=|baseurl=|g' \
      -e 's|http://mirror.centos.org/centos|https://vault.centos.org/centos|g' \
      -e 's|http://vault.centos.org/centos|https://vault.centos.org/centos|g' \
      -e '/^\[/a skip_if_unavailable=1' \
      /etc/yum.repos.d/*.repo
RUN yum clean all
RUN yum update -y

RUN yum -y install java-11-openjdk \
      rsync \
      openssl \
      rsyslog \
      python3-libselinux \
      openldap \
      openldap-servers \
      openldap-clients \
      openldap-devel \
      nss-pam-ldapd \
      krb5-libs \
      krb5-server \
      krb5-workstation \
      unzip

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN echo $'[Confluent.clients]\n\
name=Confluent repository (clients)\n\
baseurl={{ CLIENT_REPO_URL }}/clients/rpm/centos/\$releasever/\$basearch\n\
gpgcheck=1\n\
gpgkey={{ CLIENT_REPO_URL }}/clients/rpm/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}\n\
gpgcheck=1\n\
gpgkey={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry-plugins \
      confluent-ce-kafka-https-server \
      confluent-ce-kafka-rest \
      confluent-hub-client
