FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      procps \
      software-properties-common \
      openjdk-11-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

RUN wget -qO - https://packages.confluent.io/clients/deb/archive.key | sudo apt-key add - && \
    add-apt-repository "deb https://packages.confluent.io/clients/deb/ buster main" && \
    apt-get update

RUN wget -qO - https://packages.confluent.io/deb/6.2/archive.key | sudo apt-key add - && \
   add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.2 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry