FROM {{ item.image }}
LABEL maintainer="CP Ansible"
# Updated: 2024-11-21 - Python 3.8 for Ansible 2.16+ compatibility
ENV container=docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Fix EOL Mirror issue
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

# To install config manager
RUN yum -y install dnf-plugins-core

# To enable powertools repo which contains openldap-servers pkg
RUN yum -y config-manager --set-enabled powertools

# Install requirements.
RUN yum -y install rpm \
 && yum -y update \
 && yum -y install sudo vim-enhanced \
 && yum install -y jq \
 && yum clean all

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd"]

RUN yum -y install java-11-openjdk \
      rsync \
      openssl \
      procps \
      procps-ng \
      python38

# Set python3.8 as the default python3
RUN alternatives --set python3 /usr/bin/python3.8 || ln -sf /usr/bin/python3.8 /usr/bin/python3
