FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl \
      rsyslog \
      libselinux-python \
      openldap \
      openldap-servers \
      compat-openldap \
      openldap-clients \
      openldap-devel \
      nss-pam-ldapd \
      libselinux-python \
      krb5-libs \
      krb5-server \
      krb5-workstation \
      unzip

RUN echo $'[Confluent.clients]\n\
name=Confluent repository (clients)\n\
baseurl=https://packages.confluent.io/clients/rpm/centos/7/x86_64\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/clients/rpm/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl=https://packages.confluent.io/rpm/6.2\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/6.2/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry \
      confluent-ce-kafka-https-server \
      confluent-ce-kafka-rest \
      confluent-hub-client
