FROM {{ item.image }}

# CentOS 7 is EOL: mirrorlist.centos.org is decommissioned (DNS gone) and
# mirror.centos.org is retired. Disable the dead mirrorlists and point every
# repo at the frozen vault.centos.org tree over HTTPS -- plain http now
# 301-redirects to https and CentOS 7's old curl then gets a 403 from CloudFront.
# vault/EPEL are also flaky (intermittent CDN 403s / empty replies); since every
# OS package is baked into this image below, mark these repos skip_if_unavailable
# so a metadata refresh miss at converge time can't abort the run.
RUN sed -i \
      -e 's|^mirrorlist=|#mirrorlist=|g' \
      -e 's|^#\s*baseurl=|baseurl=|g' \
      -e 's|http://mirror.centos.org/centos|https://vault.centos.org/centos|g' \
      -e 's|http://vault.centos.org/centos|https://vault.centos.org/centos|g' \
      -e '/^\[/a skip_if_unavailable=1' \
      /etc/yum.repos.d/*.repo
RUN yum clean all
RUN yum update -y

# Download Java using wget

RUN yum -y install wget curl
RUN wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
RUN tar xvf openjdk-17.0.2_linux-x64_bin.tar.gz
RUN sudo mv jdk-17.0.2/ /opt/jdk17/
RUN rm -rf openjdk-17.0.2_linux-x64_bin.tar.gz

RUN yum -y install rsync \
      openssl

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}
