FROM {{ item.image }}

# replace mirror.centos.org with vault.centos.org as centos7 is eol and this url does not work now.
RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
RUN yum update -y

# RUN yum -y install java-11-openjdk \
#       rsync \
#       openssl

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('http://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz {{ COMMON_REPO_URL }}/archive/{{ REPO_VER }}/confluent-{{ PACKAGE_VER }}.tar.gz && \
    tar xzf /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-{{ PACKAGE_VER }}.tar.gz

