FROM {{ item.image }}

# Download Java using wget

RUN wget https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz
RUN tar xvf openjdk-17.0.1_linux-x64_bin.tar.gz
RUN sudo mv jdk-17*/ /opt/jdk17
RUN rm -rf openjdk-17.0.1_linux-x64_bin.tar.gz

RUN echo 'deb [check-valid-until=no] http://archive.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list

RUN sed -i s/ftp.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i s/security.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i '/stretch-updates/d' /etc/apt/sources.list
RUN sed -i s/ftp.debian.org/archive.debian.org/g /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl \
      git \
      libssl-dev \
      zlib1g-dev \
      libbz2-dev \
      libreadline-dev \
      libsqlite3-dev \
      libffi-dev \
      libncurses5-dev \
      liblzma-dev \
      libgdbm-dev \
      libnss3-dev \
      libdb-dev

# Hack to fix cacerts on debian hosts, preventing confluenthub installs from working
RUN mkdir -p /etc/ssl/certs/java/
RUN mkdir -p /usr/share/java/
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts && \
    /var/lib/dpkg/info/ca-certificates.postinst configure

RUN curl https://pyenv.run | bash

# Set up pyenv environment variables
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# Install Python 3.6 using pyenv
RUN pyenv install 3.6.15 && \
    pyenv global 3.6.15 && \
    ln -sf /root/.pyenv/versions/3.6.15/bin/python3.6 /usr/bin/python3

RUN rm /usr/bin/lsb_release

# Ensure pip is installed and linked to the default Python interpreter
RUN apt-get install --no-install-recommends --yes python-pip && \
    ln -sf /usr/bin/pip /usr/bin/pip2 && \
    ln -sf /usr/bin/python /usr/bin/python2