FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-21-jdk wget gnupg vim jq && \
    apt-get install -y dirmngr python3-debian

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}
{% set CLIENT_REPO_URL = lookup('env', 'CLIENT_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN wget -qO /usr/share/keyrings/confluent-clients-archive-keyring.gpg {{ CLIENT_REPO_URL }}/clients/deb/archive.key && \
    echo "Types: deb\nURIs: {{ CLIENT_REPO_URL }}/clients/deb/\nSuites: noble\nComponents: main\nSigned-By: /usr/share/keyrings/confluent-clients-archive-keyring.gpg" > /etc/apt/sources.list.d/confluent-clients.sources && \
    apt-get update

RUN wget -qO /usr/share/keyrings/confluent-archive-keyring.gpg {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }}/archive.key && \
    echo "Types: deb\nURIs: {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }}\nSuites: stable\nComponents: main\nSigned-By: /usr/share/keyrings/confluent-archive-keyring.gpg" > /etc/apt/sources.list.d/confluent-common.sources && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-schema-registry-plugins
