FROM {{ item.image }}

RUN echo 'deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update && \
    apt-get install --no-install-recommends --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-11-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

# Hack to fix cacerts on debian hosts, preventing confluenthub installs from working
RUN /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts && \
    /var/lib/dpkg/info/ca-certificates-java.postinst configure

RUN wget -qO - https://packages.confluent.io/clients/deb/archive.key | sudo apt-key add - && \
    add-apt-repository "deb https://packages.confluent.io/clients/deb/ stretch stable main" && \
    apt-get update

RUN wget -qO - https://packages.confluent.io/deb/6.2/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.2 stable main" && \
    apt-get update

RUN apt-get install --yes \
     confluent-common \
     confluent-hub-client \
     confluent-rebalancer \
     confluent-rest-utils \
     confluent-metadata-service \
     confluent-server \
     confluent-kafka-connect-replicator \
     confluent-kafka-rest \
     confluent-ksqldb \
     confluent-schema-registry \
     confluent-security \
     confluent-control-center-fe \
     confluent-control-center \
     confluent-schema-registry
