---
- name: Add Topics and Create data for Replication
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: variables

    - name: Create topic on Cluster1
      shell: |
        {{ binary_base_path }}/bin/kafka-topics --create --topic test-replicator-source \
          --bootstrap-server mds-kafka-broker1:9091 \
          --command-config /opt/confluent/etc/kafka/client.properties \
          --replication-factor 1 --partitions 1
      run_once: true
      register: output
      failed_when:
        - "'Topic test-replicator-source already exists' not in output.stdout"
        - "'Created topic test-replicator-source' not in output.stdout"

    - name: Create Topic Data
      shell: |
        seq 10 | {{ binary_base_path }}/bin/kafka-console-producer --topic test-replicator-source \
         --broker-list mds-kafka-broker1:9091 --producer.config /opt/confluent/etc/kafka/client.properties
      run_once: true
