---
### Verify playbook for USM Client Metrics properties

- name: Verify USM Client Metrics - Kafka Controller
  hosts: kafka_controller
  gather_facts: false
  tasks:
    - name: Import variables role
      import_role:
        name: variables

    - name: Verify USM Client Metrics - usm.push.enabled (Controller)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: confluent.telemetry.external.client.metrics.usm.push.enabled
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - push.enabled (Controller)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: confluent.telemetry.external.client.metrics.push.enabled
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - delta.temporality (Controller)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: confluent.telemetry.external.client.metrics.delta.temporality
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - subscription.interval.ms.list (Controller)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: confluent.telemetry.external.client.metrics.subscription.interval.ms.list
        expected_value: "60000"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - subscription.metrics.list (Controller)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/controller/server.properties
        property: confluent.telemetry.external.client.metrics.subscription.metrics.list
        expected_value: "test-org.apache.kafka.consumer.fetch.manager.fetch.latency.avg,org.apache.kafka.consumer.connection.creation.total,org.apache.kafka.consumer.fetch.manager.fetch.total,org.apache.kafka.consumer.fetch.manager.bytes.consumed.rate,org.apache.kafka.consumer.request.total,org.apache.kafka.producer.bufferpool.wait.ratio,org.apache.kafka.producer.record.queue.time.avg,org.apache.kafka.producer.request.latency.avg,org.apache.kafka.producer.produce.throttle.time.avg,org.apache.kafka.producer.connection.creation.total,org.apache.kafka.producer.request.total,org.apache.kafka.producer.topic.byte.rate"
      when: usm_client_metrics_enabled | default(false)

- name: Verify USM Client Metrics - Kafka Broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Import variables role
      import_role:
        name: variables

    - name: Verify USM Client Metrics - usm.push.enabled (Broker)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.telemetry.external.client.metrics.usm.push.enabled
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - push.enabled (Broker)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.telemetry.external.client.metrics.push.enabled
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - delta.temporality (Broker)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.telemetry.external.client.metrics.delta.temporality
        expected_value: "true"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - subscription.interval.ms.list (Broker)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.telemetry.external.client.metrics.subscription.interval.ms.list
        expected_value: "60000"
      when: usm_client_metrics_enabled | default(false)

    - name: Verify USM Client Metrics - subscription.metrics.list (Broker)
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: confluent.telemetry.external.client.metrics.subscription.metrics.list
        expected_value: "org.apache.kafka.consumer.fetch.manager.fetch.latency.avg,org.apache.kafka.consumer.connection.creation.total,org.apache.kafka.consumer.fetch.manager.fetch.total,org.apache.kafka.consumer.fetch.manager.bytes.consumed.rate,org.apache.kafka.consumer.request.total,org.apache.kafka.producer.bufferpool.wait.ratio,org.apache.kafka.producer.record.queue.time.avg,org.apache.kafka.producer.request.latency.avg,org.apache.kafka.producer.produce.throttle.time.avg,org.apache.kafka.producer.connection.creation.total,org.apache.kafka.producer.request.total,org.apache.kafka.producer.topic.byte.rate"
      when: usm_client_metrics_enabled | default(false)
