FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-6.2.0.tar.gz http://packages.confluent.io/archive/6.2/confluent-6.2.0.tar.gz && \
    tar xzf /opt/confluent/confluent-6.2.0.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-6.2.0.tar.gz
