FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-8-jdk wget gnupg

# TODO revert back
# RUN wget -qO - https://packages.confluent.io/deb/5.5/archive.key | sudo apt-key add - && \
#     add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.5 stable main" && \
#     apt-get update

# RUN apt-get install --yes \
#       confluent-common=5.5.0-1 \
#       confluent-hub-client=5.5.0-1 \
#       confluent-rebalancer=5.5.0-1 \
#       confluent-rest-utils=5.5.0-1 \
#       confluent-metadata-service=5.5.0-1 \
#       confluent-server=5.5.0-1 \
#       confluent-security=5.5.0-1 \
#       confluent-kafka-connect-replicator=5.5.0-1 \
#       confluent-kafka-rest=5.5.0-1 \
#       confluent-ksqldb=5.5.0-1 \
#       confluent-schema-registry=5.5.0-1 \
#       confluent-security=5.5.0-1 \
#       confluent-control-center-fe=5.5.0-1 \
#       confluent-control-center=5.5.0-1 \
#       confluent-schema-registry=5.5.0-1

RUN wget -qO - https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.0.x/161/deb/6.0/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.0.x/161/deb/6.0 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry
