FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-8-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

{% set DEFAULT_PACKAGE_VER = lookup('pipe', "awk '/confluent_package_version:/ {print $2}' $MOLECULE_PROJECT_DIRECTORY/roles/confluent.variables/defaults/main.yml" ) %}
{% set PACKAGE_VER = lookup('env', 'VERSION') | default(DEFAULT_PACKAGE_VER, true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN wget -qO - {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }}/archive.key | sudo apt-key add - && \
   add-apt-repository "deb [arch=amd64] {{ COMMON_REPO_URL }}/deb/{{ REPO_VER }} stable main" && \
   apt-get update

RUN apt-get install --yes \
     confluent-common={{ PACKAGE_VER }}-1 \
     confluent-hub-client={{ PACKAGE_VER }}-1 \
     confluent-rebalancer={{ PACKAGE_VER }}-1 \
     confluent-rest-utils={{ PACKAGE_VER }}-1 \
     confluent-metadata-service={{ PACKAGE_VER }}-1 \
     confluent-server={{ PACKAGE_VER }}-1 \
     confluent-kafka-connect-replicator={{ PACKAGE_VER }}-1 \
     confluent-kafka-rest={{ PACKAGE_VER }}-1 \
     confluent-ksqldb={{ PACKAGE_VER }}-1 \
     confluent-schema-registry={{ PACKAGE_VER }}-1 \
     confluent-security={{ PACKAGE_VER }}-1 \
     confluent-control-center-fe={{ PACKAGE_VER }}-1 \
     confluent-control-center={{ PACKAGE_VER }}-1 \
     confluent-schema-registry={{ PACKAGE_VER }}-1
