FROM {{ item.image }}

RUN yum -y install java-1.8.0-openjdk \
      rsync \
      openssl \
      rsyslog \
      libselinux-python \
      openldap \
      openldap-servers \
      compat-openldap \
      openldap-clients \
      openldap-devel \
      nss-pam-ldapd \
      libselinux-python \
      krb5-libs \
      krb5-server \
      krb5-workstation \
      unzip

{% set PACKAGE_VER = lookup('env', 'VERSION') | default('5.5.8', true) %}
{% set REPO_VER = PACKAGE_VER | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') %}
{% set COMMON_REPO_URL = lookup('env', 'COMMON_REPO_URL') | default('https://packages.confluent.io', true) %}

RUN echo $'[Confluent.dist]\n\
name=Confluent repository (dist)\n\
baseurl={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}/7\n\
gpgcheck=1\n\
gpgkey={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}\n\
gpgcheck=1\n\
gpgkey={{ COMMON_REPO_URL }}/rpm/{{ REPO_VER }}/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common-{{ PACKAGE_VER }}-1 \
      confluent-rebalancer-{{ PACKAGE_VER }}-1 \
      confluent-rest-utils-{{ PACKAGE_VER }}-1 \
      confluent-metadata-service-{{ PACKAGE_VER }}-1 \
      confluent-server-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-elasticsearch-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-jdbc-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-jms-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-replicator-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-s3-{{ PACKAGE_VER }}-1 \
      confluent-kafka-connect-storage-common-{{ PACKAGE_VER }}-1 \
      confluent-kafka-rest-{{ PACKAGE_VER }}-1 \
      confluent-ksqldb-{{ PACKAGE_VER }}-1 \
      confluent-schema-registry-{{ PACKAGE_VER }}-1 \
      confluent-security-{{ PACKAGE_VER }}-1 \
      confluent-control-center-fe-{{ PACKAGE_VER }}-1 \
      confluent-control-center-{{ PACKAGE_VER }}-1 \
      confluent-schema-registry-{{ PACKAGE_VER }}-1
