FROM {{ item.image }}

RUN yum -y install java-1.8.0-openjdk \
      rsync \
      openssl \
      rsyslog \
      libselinux-python \
      openldap \
      openldap-servers \
      compat-openldap \
      openldap-clients \
      openldap-devel \
      nss-pam-ldapd \
      libselinux-python \
      krb5-libs \
      krb5-server \
      krb5-workstation \
      unzip

# TODO go to official packages
# Rpm Packages: https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/rpm/5.5

RUN echo $'[Confluent.dist]\n\
name=Confluent repository (dist)\n\
baseurl=https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/rpm/5.5/7\n\
gpgcheck=1\n\
gpgkey=https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/rpm/5.5/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl=https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/rpm/5.5\n\
gpgcheck=1\n\
gpgkey=https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/rpm/5.5/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service-5.4.0-1  \
      confluent-server \
      confluent-kafka-connect-elasticsearch \
      confluent-kafka-connect-jdbc \
      confluent-kafka-connect-jms \
      confluent-kafka-connect-replicator \
      confluent-kafka-connect-s3 \
      confluent-kafka-connect-storage-common \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry
