FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-8-jdk wget gnupg

RUN wget -qO - https://s3-us-west-2.amazonaws.com/staging-confluent-packages-6.1.0/deb/6.0/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/staging-confluent-packages-6.1.0/deb/6.0 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-hub-client \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-security \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry
