FROM {{ item.image }}

RUN yum -y install java-1.8.0-openjdk \
      rsync \
      openssl \
      rsyslog \
      libselinux-python \
      openldap \
      openldap-servers \
      compat-openldap \
      openldap-clients \
      openldap-devel \
      nss-pam-ldapd \
      libselinux-python \
      krb5-libs \
      krb5-server \
      krb5-workstation \
      unzip

RUN echo $'[Confluent.dist]\n\
name=Confluent repository (dist)\n\
baseurl=https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.0.x/60/rpm/6.0\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
enabled=1\n\
\n\
[Confluent]\n\
name=Confluent repository\n\
baseurl=https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/6.0.x/60/rpm/6.0\n\
gpgcheck=1\n\
gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
enabled=1' >> /etc/yum.repos.d/confluent.repo

RUN yum clean all && \
    yum -y install confluent-common \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service \
      confluent-server \
      confluent-kafka-connect-replicator \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry \
      confluent-ce-kafka-https-server \
      confluent-ce-kafka-rest \
      confluent-hub-client

## TO DO: Remove nightly build

# RUN echo $'[Confluent.dist]\n\
# name=Confluent repository (dist)\n\
# baseurl=https://packages.confluent.io/rpm/5.5/7\n\
# gpgcheck=1\n\
# gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
# enabled=1\n\
# \n\
# [Confluent]\n\
# name=Confluent repository\n\
# baseurl=https://packages.confluent.io/rpm/5.5\n\
# gpgcheck=1\n\
# gpgkey=https://packages.confluent.io/rpm/5.5/archive.key\n\
# enabled=1' >> /etc/yum.repos.d/confluent.repo

# RUN yum clean all && \
#     yum -y install confluent-common-5.5.0-1 \
#       confluent-rebalancer-5.5.0-1 \
#       confluent-rest-utils-5.5.0-1 \
#       confluent-metadata-service-5.5.0-1 \
#       confluent-server-5.5.0-1 \
#       confluent-kafka-connect-replicator-5.5.0-1 \
#       confluent-kafka-rest-5.5.0-1 \
#       confluent-ksqldb-5.5.0-1 \
#       confluent-schema-registry-5.5.0-1 \
#       confluent-security-5.5.0-1 \
#       confluent-control-center-fe-5.5.0-1 \
#       confluent-control-center-5.5.0-1 \
#       confluent-schema-registry-5.5.0-1
