FROM {{ item.image }}

RUN mkdir -p /usr/share/man/man1 && \
    apt-get update -y && \
    apt-get install -y openjdk-8-jdk wget gnupg

RUN wget -qO - https://packages.confluent.io/deb/6.0/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.0 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common=6.0.0-1 \
      confluent-hub-client=6.0.0-1 \
      confluent-rebalancer=6.0.0-1 \
      confluent-rest-utils=6.0.0-1 \
      confluent-metadata-service=6.0.0-1 \
      confluent-server=6.0.0-1 \
      confluent-security=6.0.0-1 \
      confluent-kafka-connect-replicator=6.0.0-1 \
      confluent-kafka-rest=6.0.0-1 \
      confluent-ksqldb=6.0.0-1 \
      confluent-schema-registry=6.0.0-1 \
      confluent-security=6.0.0-1 \
      confluent-control-center-fe=6.0.0-1 \
      confluent-control-center=6.0.0-1 \
      confluent-schema-registry=6.0.0-1
