FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-8-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

RUN wget -qO - https://packages.confluent.io/deb/5.5/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.5 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common=5.5.7-1 \
      confluent-rebalancer=5.5.7-1 \
      confluent-rest-utils=5.5.7-1 \
      confluent-metadata-service=5.5.7-1 \
      confluent-server=5.5.7-1 \
      confluent-kafka-connect-elasticsearch=5.5.7-1 \
      confluent-kafka-connect-jdbc=5.5.7-1 \
      confluent-kafka-connect-jms=5.5.7-1 \
      confluent-kafka-connect-replicator=5.5.7-1 \
      confluent-kafka-connect-s3=5.5.7-1 \
      confluent-kafka-connect-storage-common=5.5.7-1 \
      confluent-kafka-rest=5.5.7-1 \
      confluent-ksqldb=5.5.7-1 \
      confluent-schema-registry=5.5.7-1 \
      confluent-security=5.5.7-1 \
      confluent-control-center-fe=5.5.7-1 \
      confluent-control-center=5.5.7-1 \
      confluent-schema-registry=5.5.7-1
