FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-6.1.0.tar.gz https://s3-us-west-2.amazonaws.com/staging-confluent-packages-6.1.0/archive/6.1/confluent-6.1.0.tar.gz && \
    tar xzf /opt/confluent/confluent-6.1.0.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-6.1.0.tar.gz
