FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-8-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl

# TODO go w official repo link
# Deb Packages: https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/deb/5.5

RUN wget -qO - https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/deb/5.5/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/staging-confluent-packages-5.5.0/deb/5.5 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common \
      confluent-rebalancer \
      confluent-rest-utils \
      confluent-metadata-service  \
      confluent-server \
      confluent-kafka-connect-elasticsearch \
      confluent-kafka-connect-jdbc \
      confluent-kafka-connect-jms \
      confluent-kafka-connect-replicator \
      confluent-kafka-connect-s3 \
      confluent-kafka-connect-storage-common \
      confluent-kafka-rest \
      confluent-ksqldb \
      confluent-schema-registry \
      confluent-security \
      confluent-control-center-fe \
      confluent-control-center \
      confluent-schema-registry
