FROM {{ item.image }}

RUN apt-get update && \
    apt-get install --yes \
      apt-transport-https \
      gnupg \
      software-properties-common \
      openjdk-11-jdk \
      rsync \
      ca-certificates \
      openssl \
      unzip \
      curl
