---
- name: Get ClusterId
  command: "{{ binary_base_path }}/bin/kafka-storage random-uuid"
  environment:
    KAFKA_OPTS: "-Xlog:all=error -XX:+IgnoreUnrecognizedVMOptions"
  register: uuid_key
  changed_when: false
  run_once: true

- name: Get existing master key from override.conf
  include_role:
    name: common
    tasks_from: get_masterkey.yml
  vars:
    systemd_override_path: "{{ kafka_controller.systemd_override }}"
  when: kafka_controller_secrets_protection_enabled|bool
  tags:
    - get_existing_masterkey_from_override_conf

- name: Format Data Directory
  command: "{{ binary_base_path }}/bin/kafka-storage format -t={{ clusterid }} -c {{ kafka_controller.config_file }} --ignore-formatted"
  environment: "{{ {'CONFLUENT_SECURITY_MASTER_KEY': existing_masterkey} if kafka_controller_secrets_protection_enabled|bool and existing_masterkey | default('') != '' else {} }}"
  register: format_meta
  changed_when: format_meta.rc == 0
  no_log: "{{mask_secrets|bool}}"
  vars:
    clusterid: "{{ uuid_key.stdout }}"
