---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_controller_service_name}}"
    state: restarted
  when: not (rootless_enabled | bool)
  tags:
    - systemd

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_controller_health_check_delay }}"
