FROM {{ item.image }}

RUN apt-get update && \
    apt-get install apt-transport-https -y --force-yes && \
    apt-get install gnupg -y && \
    apt-get install software-properties-common -y && \
    apt-get install openjdk-8-jdk -y

RUN wget -qO - https://packages.confluent.io/deb/5.4/archive.key | sudo apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4 stable main" && \
    apt-get update

RUN apt-get install --yes \
      confluent-common=5.4.0-1 \
      confluent-rebalancer=5.4.0-1 \
      confluent-rest-utils=5.4.0-1 \
      confluent-metadata-service=5.4.0-1  \
      confluent-server=5.4.0-1 \
      confluent-kafka-connect-elasticsearch=5.4.0-1 \
      confluent-kafka-connect-jdbc=5.4.0-1 \
      confluent-kafka-connect-jms=5.4.0-1 \
      confluent-kafka-connect-replicator=5.4.0-1 \
      confluent-kafka-connect-s3=5.4.0-1 \
      confluent-kafka-connect-storage-common=5.4.0-1 \
      confluent-kafka-rest=5.4.0-1 \
      confluent-ksql=5.4.0-1 \
      confluent-schema-registry=5.4.0-1 \
      confluent-security=5.4.0-1 \
      confluent-control-center-fe=5.4.0-1 \
      confluent-control-center=5.4.0-1 \
      confluent-schema-registry=5.4.0-1
