---
- name: restart usm agent
  include_tasks: tasks/restart_and_wait.yml
  when:
    - not usm_agent_skip_restarts

- name: restart command handler
  include_tasks: tasks/restart_command_handler.yml
  when:
    - not usm_agent_skip_restarts
