FROM {{ item.image }}

RUN echo "[Confluent.dist]\n\
baseurl = http://jenkins-confluent-packages.s3-us-west-2.amazonaws.com/5.4.x/42/rpm/5.4\n\
enabled = 1\n\
gpgcheck = 1\n\
gpgkey = http://jenkins-confluent-packages.s3-us-west-2.amazonaws.com/5.4.x/42/rpm/5.4/archive.key\n\
name = Confluent repository (dist)\n\
\n\
[Confluent]\n\
baseurl = http://jenkins-confluent-packages.s3-us-west-2.amazonaws.com/5.4.x/42/rpm/5.4\n\
enabled = 1\n\
gpgcheck = 1\n\
gpgkey = http://jenkins-confluent-packages.s3-us-west-2.amazonaws.com/5.4.x/42/rpm/5.4/archive.key\n\
name = Confluent repository" >> /etc/yum.repos.d/confluent.repo && \
  yum clean all && \
  yum -y install confluent-platform-2.12 && \
  yum -y remove confluent-kafka-2.12 && \
  yum -y install confluent-server
