---
- name: Get Java Path
  shell: dirname $(dirname $(readlink -f $(which java)))
  register: java_path
  changed_when: false

- name: Disable JVM level FIPS
  lineinfile:
    path: "{{java_path.stdout}}/conf/security/java.security"
    search_string: 'security.useSystemPropertiesFile=true'
    line: security.useSystemPropertiesFile=false
    owner: root
    group: root
    mode: '644'
  when: redhat_java_package_name in ['java-17-openjdk', 'java-21-openjdk']

- name: Disable JVM level FIPS (JDK 25+)
  lineinfile:
    path: "{{java_path.stdout}}/conf/security/redhat/crypto-policies.properties"
    regexp: '^include true/crypto-policies.properties$'
    line: 'include false/crypto-policies.properties'
    owner: root
    group: root
    mode: '644'
  when: redhat_java_package_name in ['java-25-openjdk']

- name: Configure crypto policies for Redhat
  command: update-crypto-policies --set FIPS
  become: true
  changed_when: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ['8', '9']
