---
- name: Configure IPv6 Preference
  import_playbook: ../configure_ipv6.yml

- name: Provision Kerberos Server
  import_playbook: ../kerberos.yml

# BYOP: distribute the mock Prometheus CA to the hosts that connect to it.
- import_playbook: ../byop_distribute_ca.yml
