---
- name: Stop a Surviving Controller Process
  hosts: controller3
  gather_facts: false
  tasks:
    - import_role:
        name: variables

    - name: Stop Kafka Controller
      systemd:
        name: "{{ kafka_controller_service_name }}"
        state: stopped

- name: Fail a Controller Host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop Controller Container
      community.docker.docker_container:
        name: controller2
        state: stopped

- name: Recover the Controller Quorum
  import_playbook: confluent.platform.KRaftQuorumRecovery
